name = "SatelliteAnalysis"
uuid = "101040f3-2a13-4d8c-b9b0-4a720fa906ce"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.3.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrettyNumbers = "d1bdb62b-d559-469f-b147-fd8a93502a34"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ReferenceFrameRotations = "74f56ac7-18b3-5285-802d-d4bd4f104033"
SatelliteToolbox = "6ac157d9-b43d-51bb-8fab-48bf53814f4a"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"

[extensions]
SatelliteAnalysisPlottingExt = ["GeoMakie"]

[compat]
DataFrames = "1"
GeoMakie = "0.6"
PrettyNumbers = "0.2"
Reexport = "1"
ReferenceFrameRotations = "3"
SatelliteToolbox = "0.12.2"
Scratch = "1.2"
StaticArrays = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[targets]
test = ["Test", "Logging"]
